title: Computech Limited
email: your@computechlimted.com
description: "East & Central Africa's Leading Technology System Provider"
url: ""
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: 
  - _pages