title: Computech Limited
email: info@computechlimted.com
description: "East & Central Africa's Leading Technology System Provider"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-redirect-from
sass:
  style: compressed

collections:
  news:
    output: true 

pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "tags.md"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"
url: 'https://www.computechlimited.com'
github: onweru
repo: compute
branch: master
mailchimp:
  url: ''
  hidden: ''
  validate: '' 
formcarry: 'ZJiOuD36e70'
exclude:
  - Gemfile
  - Rakefile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE.md

include: 
  - _pages
  - _devices

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news-post"
      author: Computech
      permalink: /:title/
      image: cyber-security
  -
    scope:
      path: "_news"
      type: "news"
    values:
      layout: "news-post"
      author: Computech
      permalink: /news/:title/
  -
    scope:
      path: "_devices"
      type: "pages"
    values:
      layout: "device"
      full: true