title: Computech Limited
email: info@computechlimted.com
description: "East & Central Africa's Leading Technology System Provider"
url: ""
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-redirect-from
sass:
  style: compressed

pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "tags.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

include: 
  - _pages