title = "Computech Limited"
baseurl = "https://www.computechlimited.com"
paginate = 11
[params]
email = "info@computechlimted.com"
hr = "HRKenya@computechlimited.com"
description = "East & Central Africa's Leading Technology System Provider"
logo = "/images/logo.png"
twitter = "@wearecomputech"
url = "https://www.computechlimited.com"
author = "Computech Limited"

[permalinks]
  blog = "/:title/"
  news = "/:title/"

[minify]
  minifyOutput = false
  
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
