title = "Computech Limited"
baseurl = "https://www.computechlimited.com"
paginate = 10
[params]
email = "info@computechlimted.com"
hr = "HRKenya@computechlimited.com"
description = "East & Central Africa's Leading Technology System Provider"
logo = "/images/logo.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false


# defaults:
#   -
#     scope:
#       path: "_posts"
#       type: "posts"
#     values:
#       layout: "news-post"
#       author: Computech
#       permalink: /:title/
#       image: cyber-security
#   -
#     scope:
#       path: "_news"
#       type: "news"
#     values:
#       layout: "news-post"
#       author: Computech
#       permalink: /news/:title/
#   -
#     scope:
#       path: "_devices"
#       type: "pages"
#     values:
#       layout: "device"
#       full: true
